# Generated by Django 5.0.3 on 2024-04-07 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field=200, null=True, upload_to='posts/', width_field=200),
        ),
        migrations.AddField(
            model_name='post',
            name='is_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location_tag',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
