# Generated by Django 5.0.3 on 2024-04-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_created_at_post_image_post_is_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uploaded_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
