# Generated by Django 5.0.3 on 2024-04-09 16:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_likes', '0001_initial'),
        ('posts', '0004_rename_uploaded_at_post_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_like',
            new_name='PostLike',
        ),
    ]
