# Generated by Django 5.0.3 on 2024-04-08 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_uploaded_at_comment_updated_at_and_more'),
        ('recomments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomment',
            old_name='uploaded_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='recomment',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomments', to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
