# Generated by Django 5.0.3 on 2024-04-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomments', '0002_rename_uploaded_at_recomment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomment',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
